import { createFileRoute } from "@tanstack/react-router";
// Fix (frontend2.0 migration): these components live in "components/landing"
// (the folder was renamed after being generated by Lovable under "portfolio-landing";
// the real name on disk was always "landing"). Import corrected to match
// the real folder, without touching any section's logic.
import { Hero } from "@/components/landing/Hero";
import { ProblemSection } from "@/components/landing/ProblemSection";
import { HowItWorks } from "@/components/landing/HowItWorks";
import { MetricsCounters } from "@/components/landing/MetricsCounters";
import { TechStack } from "@/components/landing/TechStack";
import { SecuritySection } from "@/components/landing/SecuritySection";
import { UXSection } from "@/components/landing/UXSection";
import { ArchitectureDecisions } from "@/components/landing/ArchitectureDecisions";
import { DemoSection } from "@/components/landing/DemoSection";
import { FinalCTA } from "@/components/landing/FinalCTA";
import { ThankYouBand } from "@/components/landing/ThankYouBand";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      {
        title:
          "Crowdfunding DApp — Solidity + web3 frontend engineering case study",
      },
      {
        name: "description",
        content:
          "On-chain crowdfunding dApp: funds that never get stuck, no middlemen, transient reentrancy protection, static analysis, and a production stack.",
      },
      {
        property: "og:title",
        content: "Crowdfunding DApp — on-chain case study",
      },
      {
        property: "og:description",
        content:
          "Technical portfolio of a freelance Solidity and web3 frontend engineer.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Landing,
});

function Landing() {
  return (
    <main className="min-h-screen">
      <Hero />
      <ProblemSection />
      <HowItWorks />
      <MetricsCounters />
      <TechStack />
      <SecuritySection />
      <UXSection />
      <ArchitectureDecisions />
      <DemoSection />
      <FinalCTA />
      <ThankYouBand />
    </main>
  );
}
