/**
 * E2E setup (docs/09_ROADMAP_MEJORAS.md § 12): starts a local Anvil node,
 * deploys a fresh Crowdfunding instance to it, and writes the address into
 * frontend2.0/.env.e2e.local so Playwright's dev server (started in "e2e"
 * mode, see frontend2.0/playwright.config.ts) can read it via Vite's env
 * loading (.env.e2e.local is loaded automatically when Vite runs with
 * --mode e2e).
 *
 * Usage:
 *   npm run e2e:setup        # from the repo root
 *
 * Idempotent-ish: if something is already listening on :8545 (e.g. Abraham
 * already ran `anvil` in another terminal), this script reuses it instead of
 * spawning a second node — Anvil doesn't allow two processes on the same port.
 */
import { spawn, spawnSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { setTimeout as sleep } from "node:timers/promises";

const RPC_URL = "http://127.0.0.1:8545";
const READY_TIMEOUT_MS = 15_000;
const POLL_INTERVAL_MS = 300;

async function isRpcReady(): Promise<boolean> {
  try {
    const res = await fetch(RPC_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "eth_blockNumber", params: [] }),
    });
    return res.ok;
  } catch {
    return false;
  }
}

async function waitForRpc(): Promise<void> {
  const deadline = Date.now() + READY_TIMEOUT_MS;
  while (Date.now() < deadline) {
    if (await isRpcReady()) return;
    await sleep(POLL_INTERVAL_MS);
  }
  throw new Error(`Anvil didn't answer at ${RPC_URL} within ${READY_TIMEOUT_MS}ms.`);
}

function startAnvilIfNeeded(): void {
  // Detached + unref: this script can exit while Anvil keeps running in the
  // background for the Playwright run that follows. Abraham stops it by
  // killing the printed PID (or just closing the terminal in local dev).
  const anvil = spawn("anvil", ["--silent"], { detached: true, stdio: "ignore" });

  // spawn() emits "error" ASYNCHRONOUSLY (it can't throw synchronously here,
  // since the OS lookup for the "anvil" binary happens after this call
  // returns) — without this handler, an ENOENT (Foundry not installed)
  // surfaces as an ugly "Uncaught exception" stack trace instead of a clear
  // message telling Abraham what to actually do about it.
  anvil.on("error", (error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") {
      console.error(
        "\nAnvil isn't installed (or isn't in PATH). Install Foundry first:\n" +
          "  curl -L https://foundry.paradigm.xyz | bash\n" +
          "  foundryup\n" +
          "Then confirm with: anvil --version\n" +
          "(see book.getfoundry.sh/getting-started/installation)",
      );
    } else {
      console.error(error);
    }
    process.exit(1);
  });

  anvil.unref();
  console.log(`Anvil starting in the background (PID ${anvil.pid}). Stop it later with: kill ${anvil.pid}`);
}

// Anvil's chain state is in-memory only and never survives a restart, but
// Ignition's journal for it (ignition/deployments/chain-31337/) IS persisted
// on disk. If Anvil got restarted since the last e2e:setup run (e.g. closing
// the terminal that had it, killing the detached process), Ignition still
// sees a "complete" journal from before and skips redeploying — silently
// reusing an address with NO code on the current chain (confirmed via trace:
// eth_call to nextProjectId() returned bare "0x", the empty-bytecode
// signature). Unlike testnets (Sepolia), this journal must never persist
// across runs here: Anvil is always a throwaway chain, so every e2e:setup
// run must force a real, fresh deploy.
const ANVIL_IGNITION_JOURNAL = "ignition/deployments/chain-31337";

function deployToAnvil(): void {
  if (existsSync(ANVIL_IGNITION_JOURNAL)) {
    rmSync(ANVIL_IGNITION_JOURNAL, { recursive: true, force: true });
    console.log(`Removed stale Ignition journal at ${ANVIL_IGNITION_JOURNAL} (Anvil state never persists, so neither should its deployment record).`);
  }
  console.log("Deploying Crowdfunding.sol to Anvil...");
  const result = spawnSync("npx", ["hardhat", "run", "scripts/deploy.ts", "--network", "anvil"], {
    stdio: "inherit",
    shell: true,
  });
  if (result.status !== 0) {
    throw new Error("Deploy to Anvil failed (see Hardhat output above).");
  }
}

function writeFrontendEnv(address: string): void {
  const envPath = "frontend2.0/.env.e2e.local";
  const content = `# Auto-generated by scripts/e2e-setup.ts — do not edit by hand, do not commit.\nVITE_E2E=true\nVITE_CROWDFUNDING_ADDRESS_ANVIL=${address}\n`;
  writeFileSync(envPath, content);
  console.log(`Wrote ${envPath}`);
}

async function main(): Promise<void> {
  if (await isRpcReady()) {
    console.log(`Anvil already running at ${RPC_URL}, reusing it.`);
  } else {
    startAnvilIfNeeded();
    await waitForRpc();
  }

  deployToAnvil();

  const deploymentPath = "deployments/anvil.json";
  if (!existsSync(deploymentPath)) {
    throw new Error(`${deploymentPath} not found after deploy — check the Hardhat output above.`);
  }
  const { address } = JSON.parse(readFileSync(deploymentPath, "utf8")) as { address: string };
  writeFrontendEnv(address);

  console.log(`\nReady. Crowdfunding deployed at ${address} on Anvil.`);
  console.log("Next: cd frontend2.0 && npm run test:e2e");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
